name: PKUAutoSubmit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "25 2 * * *"
    - cron: "45 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yousiki/PKUAutoSubmit-action@master
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          reason: ${{ secrets.reason }}
          wechat: "True"
          sckey: ${{ secrets.sckey }}
